### ISSUE TITLE
Changing Submodel-ID deletes submodel

### ISSUE THREAD

**Issue by JoergNeidig** [admin-shell/aasx-package-explorer#12]
1) Go to existing submodel with given id (in my case URI, generated)
2) Change id and apply change
3) Create new submodel of type instance
3) Submodel vanishes, with error message "Cannot find some submodel!"

If AASX is saved and loaded the model also does not include the submodel.

**Comment by admin-shell** [comment]
Changed handling of Submodels.
* In edit mode, all submodels are displayed by elememts ("SUB") in capital letters.
* For Submodel and SubmodelRef, first the reference is displayed (right hand side panel) before the model contents.
* Re-assign of SubmodelRefs to Submodels is possible, now
* SubmodelElements are only displayed 'under' SubmodelRefs, in order to have normalized view
