### ISSUE TITLE
Properties related to file names and file URIs get mangled

### ISSUE THREAD

**Issue by mmarseu** [admin-shell/aasx-package-explorer#2]
I used the sample AAS as a template to create my own. However, I have trouble getting my embedded files to display in the browser. Apparently, the URI in the File element gets somehow mangled. The same happens to the value of the DocFilename properties.

**To Reproduce**
1. Open the [attached AASX](https://github.com/admin-shell/aasx-package-explorer/files/2854960/CP-AM-CAM.zip) in the Aasx Package Explorer 
2. Go to AAS/documentation/\*/DocFilename or AAS/documentation/\*/File

**Expected behavior**
- The Filename should have an underscore after 'CP-AM-CAM'. Its there in the XML source
- The file URI should have three underscores after the 'http'. They're there in the XML source.
- I should be able to display the file in the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/47556460/52626178-ea366300-2eb2-11e9-848f-12ea9b95eeb1.png)
![image](https://user-images.githubusercontent.com/47556460/52626221-ffab8d00-2eb2-11e9-8e16-a1186e57f36c.png)

**Comment by admin-shell** [comment]
OK ;-) Funny! This is an expected behaviour of the WPF widget named "Label". I've now changed the widget type into <TextBlock>. This is a very fundamental change, as this basically occurs to all normal text fields on the right hand side. Hopefully, this will work for the future.
This fixes your issue.
